name = "SpikingNeuralEvolution"
uuid = "9b2170b5-66c5-4e24-ba26-bb3ddcea90e9"
authors = ["narger <52449688+narger-ef@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
